[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "isaaclab_robot_training"
version = "0.1.0"
description = "Robot Control Library for Isaac Lab"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "numpy",
]

[tool.setuptools]
packages = ["controll_scripts", "rl_manager", "rl_direct", "so_arm_mimic"]

[tool.setuptools.package-dir]
controll_scripts = "tools/controll_scripts"
rl_manager = "projects/rl_manager/source/rl_manager/rl_manager"
rl_direct  = "projects/rl_direct/source/rl_direct/rl_direct"
so_arm_mimic = "projects/so_arm_mimic"

[tool.setuptools.package-data]
controll_scripts = [
    "so_arm_101/*.usd",
    "so_arm_101/*.yaml",
    "so_arm_101/**/*.urdf",
    "so_arm_101/**/*",
]